[theme]
primaryColor = "#9A7D61"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5EDE4"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
maxUploadSize = 100
enableXsrfProtection = true

[client]
toolbarMode = "viewer"

[logger]
level = "info"

[ui]
hideTopBar = false
hideSidebarNav = false